"""initial schema

Revision ID: d123746b3cea
Revises: 
Create Date: 2026-07-17 21:42:02.413302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd123746b3cea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sa.Enum('checking', 'savings', 'cash', 'credit_card', 'other', name='accounttype'), nullable=False),
    sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('initial_balance_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount_limit_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_category_id'), 'budget', ['category_id'], unique=False)
    op.create_index(op.f('ix_budget_month'), 'budget', ['month'], unique=False)
    op.create_index(op.f('ix_budget_year'), 'budget', ['year'], unique=False)
    op.create_table('mappingtemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('date_column', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_column', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_column', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('debit_column', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credit_column', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id_column', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decimal_separator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thousands_separator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delimiter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encoding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_field', sa.Enum('description', 'amount', 'account', name='matchfield'), nullable=False),
    sa.Column('match_type', sa.Enum('contains', 'exact', 'starts_with', 'regex', name='matchtype'), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importbatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'csv', 'excel', 'pdf', name='importsource'), nullable=False),
    sa.Column('mapping_template_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='importbatchstatus'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['mapping_template_id'], ['mappingtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('expense', 'income', 'transfer', name='transactiontype'), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'csv', 'excel', 'pdf', name='importsource'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['importbatch.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_category_id'), 'transaction', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_content_hash'), 'transaction', ['content_hash'], unique=False)
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_description'), 'transaction', ['description'], unique=False)
    op.create_index(op.f('ix_transaction_external_id'), 'transaction', ['external_id'], unique=False)
    op.create_index(op.f('ix_transaction_import_batch_id'), 'transaction', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_type'), 'transaction', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_import_batch_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_external_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_description'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_content_hash'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_category_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('importbatch')
    op.drop_table('rule')
    op.drop_table('mappingtemplate')
    op.drop_index(op.f('ix_budget_year'), table_name='budget')
    op.drop_index(op.f('ix_budget_month'), table_name='budget')
    op.drop_index(op.f('ix_budget_category_id'), table_name='budget')
    op.drop_table('budget')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
